<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mappings\**" />
    <EmbeddedResource Remove="Mappings\**" />
    <None Remove="Mappings\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Company.Project.DTO\Company.Project.DTO.csproj" />
    <ProjectReference Include="..\Company.Project.Infrastructure\Company.Project.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
  </ItemGroup>

</Project>
