<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Company.Project.DTO\Company.Project.DTO.csproj" />
    <ProjectReference Include="..\Company.Project.Infrastructure\Company.Project.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
  </ItemGroup>

</Project>
